FROM thuuyen18102001/nckh2023:cnn-env-v1.4

WORKDIR /app

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]

# docker build -t thuuyen18102001/nckh2023:cnn-v1.5 -f Dockerfile.normal .
